/*
 * Swagger demo API
 * This is demo API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: frank_polet@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.specto.hoverfly.junit.core.HoverflyConfig;
import io.specto.hoverfly.junit.rule.HoverflyRule;
import io.swagger.client.ApiException;
import io.swagger.client.model.Upper;
import io.swagger.client.model.Value;
import org.junit.ClassRule;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertEquals;

/**
 * API tests for UpperApi
 */
//@Ignore
public class UpperApiTest {

    private final UpperApi api = new UpperApi();

    
    /**
     * convert input to uppercase
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */

    @ClassRule
    public static HoverflyRule hoverflyRule = HoverflyRule
            .inCaptureOrSimulationMode("c:\\frank\\hoverflydemo\\upper.json", HoverflyConfig.configs().proxyLocalHost()).printSimulationData();


    @Test
    public void upperCaseTest() throws ApiException {
        Value stringObject = new Value ();
        stringObject.setValue("this is a test");
        Upper response = api.upperCase(stringObject);

        System.out.println(" upper : result : "+response.getUpper());

        // TODO: test validations
        assertEquals("THIS IS A TEST",response.getUpper().toString());
    }
    
}
